### YamlMime:ManagedReference
items:
- uid: System.SystemException
  id: SystemException
  children:
  - System.SystemException.#ctor
  - System.SystemException.#ctor(System.String)
  - System.SystemException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.SystemException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: SystemException
  nameWithType: SystemException
  fullName: System.SystemException
  type: Class
  summary: "Funge da classe base per le eccezioni di sistema dello spazio dei nomi."
  remarks: "Questa classe viene fornita come mezzo per differenziare le eccezioni di sistema e applicazione. È la classe base di tali eccezioni come <xref:System.ArgumentException>, <xref:System.FormatException>e <xref:System.InvalidOperationException>.</xref:System.InvalidOperationException> </xref:System.FormatException> </xref:System.ArgumentException>      > [!IMPORTANT] > SystemException in quanto funge da classe base di una varietà di tipi di eccezione, il codice non deve generare un&quot;eccezione SystemException, né deve tentare di gestire un&quot;eccezione SystemException, a meno che non si intende generare nuovamente l&quot;eccezione originale.       SystemException utilizza HRESULT COR_E_SYSTEM, con il valore 0x80131501."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class SystemException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.SystemException.#ctor
  id: '#ctor'
  parent: System.SystemException
  langs:
  - csharp
  name: SystemException()
  nameWithType: SystemException.SystemException()
  fullName: System.SystemException.SystemException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.SystemException&quot;> </xref> classe."
  remarks: "Questo costruttore inizializza la <xref:System.Exception.Message%2A>proprietà della nuova istanza di un messaggio fornito dal sistema che descrive l&quot;errore, ad esempio &quot;si è verificato un errore di sistema.&quot;</xref:System.Exception.Message%2A> Questo messaggio prende in considerazione le impostazioni cultura correnti.       Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.SystemException>.</xref:System.SystemException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Un riferimento null (`Nothing` in Visual Basic). |   | <xref:System.Exception.Message%2A>| La stringa di messaggio di errore localizzato. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SystemException ();
    parameters: []
  overload: System.SystemException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.SystemException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.SystemException
  langs:
  - csharp
  name: SystemException(String)
  nameWithType: SystemException.SystemException(String)
  fullName: System.SystemException.SystemException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.SystemException&quot;> </xref> classe con un messaggio di errore specificato."
  remarks: "Il contenuto del `message` parametro deve essere comprensibile all&quot;utente. Il chiamante del costruttore è necessario per garantire che la stringa sia stata localizzata per la lingua corrente.       Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.SystemException>.</xref:System.SystemException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Un riferimento null (`Nothing` in Visual Basic). |   | <xref:System.Exception.Message%2A>| La stringa di messaggio di errore. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SystemException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Il messaggio che descrive l&quot;errore."
  overload: System.SystemException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.SystemException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.SystemException
  langs:
  - csharp
  name: SystemException(SerializationInfo,StreamingContext)
  nameWithType: SystemException.SystemException(SerializationInfo,StreamingContext)
  fullName: System.SystemException.SystemException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.SystemException&quot;> </xref> classe con dati serializzati."
  remarks: "Questo costruttore viene chiamato durante la deserializzazione per ricostituire l&quot;oggetto eccezione trasmesso su un flusso. Per ulteriori informazioni, vedere [serializzazione XML e SOAP](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: protected SystemException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Oggetto che contiene i dati oggetto serializzati."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Informazioni contestuali sull&quot;origine o destinazione."
  overload: System.SystemException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.SystemException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.SystemException
  langs:
  - csharp
  name: SystemException(String,Exception)
  nameWithType: SystemException.SystemException(String,Exception)
  fullName: System.SystemException.SystemException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inizializza una nuova istanza di <xref href=&quot;System.SystemException&quot;> </xref> classe con un messaggio di errore specificato e un riferimento all&quot;eccezione interna che è la causa dell&quot;eccezione corrente."
  remarks: "Un&quot;eccezione generata come risultato diretto di un&quot;eccezione precedente può includere un riferimento all&quot;eccezione precedente nella <xref:System.Exception.InnerException%2A>proprietà.</xref:System.Exception.InnerException%2A> Il <xref:System.Exception.InnerException%2A>proprietà restituisce lo stesso valore passato al costruttore o un riferimento null (`Nothing` in Visual Basic) se il <xref:System.Exception.InnerException%2A>proprietà non fornisce il valore di eccezione interna al costruttore.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un&quot;istanza di <xref:System.SystemException>.</xref:System.SystemException>      | Proprietà | Valore |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Il riferimento all&quot;eccezione interna. |   | <xref:System.Exception.Message%2A>| La stringa di messaggio di errore. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SystemException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Il messaggio di errore che spiega il motivo dell&quot;eccezione."
    - id: innerException
      type: System.Exception
      description: "Eccezione che è la causa dell&quot;eccezione corrente. Se il `innerException` parametro non è un riferimento null (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> in Visual Basic), l&quot;eccezione corrente viene generata in un <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blocco che gestisce l&quot;eccezione interna."
  overload: System.SystemException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.SystemException.#ctor
  parent: System.SystemException
  isExternal: false
  name: SystemException()
  nameWithType: SystemException.SystemException()
  fullName: System.SystemException.SystemException()
- uid: System.SystemException.#ctor(System.String)
  parent: System.SystemException
  isExternal: false
  name: SystemException(String)
  nameWithType: SystemException.SystemException(String)
  fullName: System.SystemException.SystemException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.SystemException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.SystemException
  isExternal: false
  name: SystemException(SerializationInfo,StreamingContext)
  nameWithType: SystemException.SystemException(SerializationInfo,StreamingContext)
  fullName: System.SystemException.SystemException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.SystemException.#ctor(System.String,System.Exception)
  parent: System.SystemException
  isExternal: false
  name: SystemException(String,Exception)
  nameWithType: SystemException.SystemException(String,Exception)
  fullName: System.SystemException.SystemException(String,Exception)
- uid: System.SystemException.#ctor*
  parent: System.SystemException
  isExternal: false
  name: SystemException
  nameWithType: SystemException.SystemException
